version: "3.4"

configs:
  trickster_config:
    file: ./trickster.conf

services:
  trickster:
    image: tricksterio/trickster:1.0-beta8
    configs:
      - source: trickster_config
        target: /etc/trickster/trickster.conf
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8082:8082"
      - "9089:9089"
